source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               lib/logback-classic-1.5.35.jar,\
               lib/logback-core-1.5.35.jar,\
               lib/slf4j-api-2.0.17.jar
