bin.includes = META-INF/,\
               lib/jakarta-regexp-1.2.jar,\
               plugin.xml,\
               icons/,\
               ganymede.jar,\
               schema/
jars.extra.classpath = lib/jakarta-regexp-1.2.jar
jars.compile.order = ganymede.jar
source.ganymede.jar = src/
output.ganymede.jar = bin/
source.ganymede.jar = src/
